version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - app:/code_app
    networks:
      - cadastre_network
      
  external_app:
    build:
      context: ./external_app
    ports:
      - "8003:8003"
    volumes:
      - external_app:/code_external_app
    networks:
      - cadastre_network

networks:
  cadastre_network:
    driver: bridge

volumes:
  app:
  external_app:
